### ISSUE TITLE
Pandas

### ISSUE THREAD

**Issue by daniviga** [gem/oq-libs#8]
Should we add `pandas`? Is not used by our code, but can be useful for users

**Comment by micheles** [comment]
How big it is? Are there problematic sub-dependencies? Do we have wheels for all platforms? Also, I assume you are talking about the tools, not hazardlib and engine. For the tools it is probably a good idea to include it.

**Comment by daniviga** [comment]
Have to check. I'm not sure I want it:

1. I don't want to make our own python distribution
2. If you are a user, you can easily install it in you venv with pip
3. if you are on a shared server, because how we have built `opt` you can easily install it via `sudo pip` or distro binary packages

On Wilson is a different story because we are also using a custom built version of Python.
